"""Added email column in users table

Revision ID: 6cb0d9e6c59e
Revises: eff32e60d16c
Create Date: 2020-08-21 12:14:50.975088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cb0d9e6c59e'
down_revision = 'eff32e60d16c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=80), nullable=False))
    op.create_unique_constraint('user_email_key', 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_email_key', 'users', type_='unique')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
