"""empty message

Revision ID: eff32e60d16c
Revises: 69fb741c3dcc
Create Date: 2020-08-21 11:53:27.749821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eff32e60d16c'
down_revision = '69fb741c3dcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_username_key', 'users', type_='unique')
    # ### end Alembic commands ###
